version: "2"

linters:
  disable-all: true
  default: none
  enable:
    - nplusone
  settings:
    custom:
      nplusone:
        type: "module"
        description: This is an example usage of a plugin linter.
